# -*- coding: utf-8 -*-
"""Test Case.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Xi5FT3gMgDWkYajNLl_3DhJFfEMQ9Pm
"""

import python_cashier as py

tran=Transaction()

tran.add_item("Ayam goreng", 2, 20_000)
tran.add_item("Pasta Gigi", 3, 15_000)

tran.print_transaksi()

tran.delete_item("Pasta Gigi")
print()
tran.print_transaksi()

tran.reset_transaksi()

tran.add_item("Ayam goreng", 2, 20_000)
tran.add_item("Pasta Gigi", 3, 15_000)

tran.total_price()

tran = Transaction()

tran.add_item("Gula Pasir", 2, 20_000)
tran.add_item("Susu", 3, 15_000)

tran.print_transaksi()

tran.update_name("Gula Pasir","Gula Merah")

tran.print_transaksi()

tran.update_quantity("Susu", 2)

tran.print_transaksi()

tran.update_price("Susu",10_000)

tran.print_transaksi()

tran.add_item("Butter", 5, 50_000)
tran.total_price()